githubConfigUrl: https://github.com/langtech-bsc
githubConfigSecret: magma-github-app
maxRunners: 20
minRunners: 5
runnerGroup: default
runnerScaleSetName: magma-runner-set
containerMode:
  type: kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes:
      - ReadWriteOnce
    storageClassName: microk8s-hostpath
    resources:
      requests:
        storage: 5Gi
  kubernetesModeServiceAccount:
    annotations: null
template:
  spec:
    containers:
      - name: runner
        image: projecteaina/actions-runner:33db537
        command:
          - /home/runner/run.sh
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: 'false'
