name: Test workflow enhanced launch job
run-name: ${{ github.actor }} is executing Test workflow enhanced launch job ðŸš€

on:
  workflow_dispatch:

jobs:
  test-workflow-job-enhanced-launch-job:
    uses: ./.github/workflows/enhanced_launch_job.yml
    secrets: inherit
    with:
      local-repo: true

      
