name: Test job enhanced launch job
run-name: ${{ github.actor }} is executing Test job enhanced launch job ðŸš€

on:
  workflow_dispatch:

jobs:
  test-workflow-job-enhanced-launch-job:
    uses: langtech-bsc/magma/.github/workflows/enhanced_launch_job.yml@33-add-yml-config-file
    secrets: inherit
    with:
      runs_on: ubuntu-latest 

      
